### ISSUE TITLE
How do I install nvidia web driver?

### ISSUE THREAD

**Issue by qcgzxw** [ezaul/EFI-Asus-ROG-X570-E#1]
I'v used your EFI and it works well in  macOS12.5.

And my Graphics is GTX1050TI and I want to install nvidia web driver for better preformance.

But after I install OCLP step by step(add boot-args change change csr-active-config stuff) and restart,It always stuck on boot screen.Can you help me with that?

**Comment by ezaul** [comment]
Good afternoon! You all right?

So MACOS no longer works with NVIDIA driver! very bug Apple adopted
the video cards from AMD works natively without having to do anything!
if you want a working Hackintosh it has to be an AMD video card


By the way I will update this EFI to Open-Core 0.8.3



Em qui., 18 de ago. de 2022 às 11:00, Owen ***@***.***>
escreveu:

**Comment by qcgzxw** [comment]
Thanks for your reply. I'll get a AMD card and try again. 
I'll be really appreciated if you can update this repo after updating OC to 0.83.
