### ISSUE TITLE
Thank you very much

### ISSUE THREAD

**Issue by 91wangmeng** [ezaul/EFI-Asus-ROG-X570-E#2]
Thank you very much. I use a 6900xt graphics card. The performance loss is a little big. Do you have any suggestions?

**Comment by ezaul** [comment]
My card is an RX 5700 xt

Do a test there

To be activated, these boards need the parameter agdpmod=pikera added in the boot-args of your config.plist.

**Comment by 91wangmeng** [comment]
@ezaul I'll try. Thanks again.

**Comment by ezaul** [comment]
https://dortania.github.io/GPU-Buyers-Guide/modern-gpus/amd-gpu.html#navi-23-series
